CREATE TABLE IF NOT EXISTS CHAT_MESSAGE
(
    id
    BIGINT
    AUTO_INCREMENT
    PRIMARY
    KEY,
    sender
    VARCHAR
(
    50
) NOT NULL,
    content TEXT NOT NULL,
    send_time DATETIME DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS chat_users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
